// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqyfasxnrnsbrojwiozc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeWZhc3hucm5zYnJvandpb3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDgwMDQsImV4cCI6MjA2Mjk4NDAwNH0.clQg_LAyuRH3bYpC0hjOO8oTMfj6tPwMW4hq4s8rvqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);